In [105]:
# 1. REST over HTTP -> static
%matplotlib notebook
import requests
import pandas as pd
import numpy as np
import plotly.express as px

In [106]:
response = requests.get("https://api.binance.com/api/v3/ticker/price")

In [107]:
response.status_code

200

In [108]:
response.content

b'[{"symbol":"ETHBTC","price":"0.02797000"},{"symbol":"LTCBTC","price":"0.00072100"},{"symbol":"BNBBTC","price":"0.00838800"},{"symbol":"NEOBTC","price":"0.00003542"},{"symbol":"QTUMETH","price":"0.00046550"},{"symbol":"EOSETH","price":"0.00030670"},{"symbol":"SNTETH","price":"0.00001700"},{"symbol":"BNTETH","price":"0.00020260"},{"symbol":"BCCBTC","price":"0.00000000"},{"symbol":"GASBTC","price":"0.00002070"},{"symbol":"BNBETH","price":"0.29980000"},{"symbol":"BTCUSDT","price":"78155.83000000"},{"symbol":"ETHUSDT","price":"2185.95000000"},{"symbol":"HSRBTC","price":"0.00000000"},{"symbol":"OAXETH","price":"0.00000000"},{"symbol":"DNTETH","price":"0.00000000"},{"symbol":"MCOETH","price":"0.00000000"},{"symbol":"ICNETH","price":"0.00000000"},{"symbol":"MCOBTC","price":"0.00000000"},{"symbol":"WTCBTC","price":"0.00000024"},{"symbol":"WTCETH","price":"0.00000000"},{"symbol":"LRCBTC","price":"0.00000052"},{"symbol":"LRCETH","price":"0.00001675"},{"symbol":"QTUMBTC","price":"0.00001628"},{"symbol":"YOYOBTC","price":"0.00000000"},{"symbol":"OMGBTC","price":"0.00003080"},{"symbol":"OMGETH","price":"0.00079100"},{"symbol":"ZRXBTC","price":"0.00000154"},{"symbol":"ZRXETH","price":"0.00009940"},{"symbol":"STRATBTC","price":"0.00000000"},{"symbol":"STRATETH","price":"0.00000000"},{"symbol":"SNGLSBTC","price":"0.00000000"},{"symbol":"SNGLSETH","price":"0.00000000"},{"symbol":"BQXBTC","price":"0.00000000"},{"symbol":"BQXETH","price":"0.00000000"},{"symbol":"KNCBTC","price":"0.00000181"},{"symbol":"KNCETH","price":"0.00039410"},{"symbol":"FUNBTC","price":"0.00000000"},{"symbol":"FUNETH","price":"0.00000146"},{"symbol":"SNMBTC","price":"0.00000057"},{"symbol":"SNMETH","price":"0.00000000"},{"symbol":"NEOETH","price":"0.00477500"},{"symbol":"IOTABTC","price":"0.00000072"},{"symbol":"IOTAETH","price":"0.00003346"},{"symbol":"LINKBTC","price":"0.00012520"},{"symbol":"LINKETH","price":"0.00447900"},{"symbol":"XVGBTC","price":"0.00000000"},{"symbol":"XVGETH","price":"0.00000247"},{"symbol":"SALTBTC","price":"0.00000000"},{"symbol":"SALTETH","price":"0.00000000"},{"symbol":"MDABTC","price":"0.00000000"},{"symbol":"MDAETH","price":"0.00000000"},{"symbol":"MTLBTC","price":"0.00000405"},{"symbol":"MTLETH","price":"0.00068340"},{"symbol":"SUBBTC","price":"0.00000000"},{"symbol":"SUBETH","price":"0.00000000"},{"symbol":"EOSBTC","price":"0.00000716"},{"symbol":"SNTBTC","price":"0.00000032"},{"symbol":"ETCETH","price":"0.00387000"},{"symbol":"ETCBTC","price":"0.00011700"},{"symbol":"MTHBTC","price":"0.00000000"},{"symbol":"MTHETH","price":"0.00000000"},{"symbol":"ENGBTC","price":"0.00000000"},{"symbol":"ENGETH","price":"0.00000000"},{"symbol":"DNTBTC","price":"0.00000186"},{"symbol":"ZECBTC","price":"0.00661100"},{"symbol":"ZECETH","price":"0.23624000"},{"symbol":"BNTBTC","price":"0.00000794"},{"symbol":"ASTBTC","price":"0.00000124"},{"symbol":"ASTETH","price":"0.00000000"},{"symbol":"DASHBTC","price":"0.00053720"},{"symbol":"DASHETH","price":"0.02084000"},{"symbol":"OAXBTC","price":"0.00000038"},{"symbol":"ICNBTC","price":"0.00000000"},{"symbol":"BTGBTC","price":"0.00091300"},{"symbol":"BTGETH","price":"0.00000000"},{"symbol":"EVXBTC","price":"0.00000000"},{"symbol":"EVXETH","price":"0.00000000"},{"symbol":"REQBTC","price":"0.00000112"},{"symbol":"REQETH","price":"0.00000000"},{"symbol":"VIBBTC","price":"0.00000051"},{"symbol":"VIBETH","price":"0.00003450"},{"symbol":"HSRETH","price":"0.00000000"},{"symbol":"TRXBTC","price":"0.00000454"},{"symbol":"TRXETH","price":"0.00016205"},{"symbol":"POWRBTC","price":"0.00000094"},{"symbol":"POWRETH","price":"0.00002760"},{"symbol":"ARKBTC","price":"0.00001679"},{"symbol":"ARKETH","price":"0.00000000"},{"symbol":"YOYOETH","price":"0.00000000"},{"symbol":"XRPBTC","price":"0.00001816"},{"symbol":"XRPETH","price":"0.00064990"},{"symbol":"MODBTC","price":"0.00000000"},{"symbol":"MODETH","price":"0.00000000"},{"symbol":"ENJBTC","price":"0.00000035"},{"symbol":"ENJETH","price":"0.00006172"},{"symbol":"STORJBTC","price":"0.00000143"},{"symbol":"STORJETH","price":"0.00000000"},{"symbol":"BNBUSDT","price":"655.54000000"},{"symbol":"VENBNB","price":"0.00000000"},{"symbol":"YOYOBNB","price":"0.00000000"},{"symbol":"POWRBNB","price":"0.00000000"},{"symbol":"VENBTC","price":"0.00000000"},{"symbol":"VENETH","price":"0.00000000"},{"symbol":"KMDBTC","price":"0.00000015"},{"symbol":"KMDETH","price":"0.00000000"},{"symbol":"NULSBNB","price":"0.00000000"},{"symbol":"RCNBTC","price":"0.00000000"},{"symbol":"RCNETH","price":"0.00000000"},{"symbol":"RCNBNB","price":"0.00000000"},{"symbol":"NULSBTC","price":"0.00000030"},{"symbol":"NULSETH","price":"0.00000000"},{"symbol":"RDNBTC","price":"0.00000000"},{"symbol":"RDNETH","price":"0.00000000"},{"symbol":"RDNBNB","price":"0.00000000"},{"symbol":"XMRBTC","price":"0.00228700"},{"symbol":"XMRETH","price":"0.04032000"},{"symbol":"DLTBNB","price":"0.00000000"},{"symbol":"WTCBNB","price":"0.00000000"},{"symbol":"DLTBTC","price":"0.00000000"},{"symbol":"DLTETH","price":"0.00000000"},{"symbol":"AMBBTC","price":"0.00000010"},{"symbol":"AMBETH","price":"0.00000000"},{"symbol":"AMBBNB","price":"0.00000000"},{"symbol":"BCCETH","price":"0.00000000"},{"symbol":"BCCUSDT","price":"0.00000000"},{"symbol":"BCCBNB","price":"0.00000000"},{"symbol":"BATBTC","price":"0.00000126"},{"symbol":"BATETH","price":"0.00010630"},{"symbol":"BATBNB","price":"0.00000000"},{"symbol":"BCPTBTC","price":"0.00000000"},{"symbol":"BCPTETH","price":"0.00000000"},{"symbol":"BCPTBNB","price":"0.00000000"},{"symbol":"ARNBTC","price":"0.00000000"},{"symbol":"ARNETH","price":"0.00000000"},{"symbol":"GVTBTC","price":"0.00000000"},{"symbol":"GVTETH","price":"0.00000000"},{"symbol":"CDTBTC","price":"0.00000000"},{"symbol":"CDTETH","price":"0.00000000"},{"symbol":"GXSBTC","price":"0.00000000"},{"symbol":"GXSETH","price":"0.00000000"},{"symbol":"NEOUSDT","price":"2.94500000"},{"symbol":"NEOBNB","price":"0.03836000"},{"symbol":"POEBTC","price":"0.00000000"},{"symbol":"POEETH","price":"0.00000000"},{"symbol":"QSPBTC","price":"0.00000000"},{"symbol":"QSPETH","price":"0.00000000"},{"symbol":"QSPBNB","price":"0.00000000"},{"symbol":"BTSBTC","price":"0.00000043"},{"symbol":"BTSETH","price":"0.00000000"},{"symbol":"BTSBNB","price":"0.00000000"},{"symbol":"XZCBTC","price":"0.00000000"},{"symbol":"XZCETH","price":"0.00000000"},{"symbol":"XZCBNB","price":"0.00000000"},{"symbol":"LSKBTC","price":"0.00000186"},{"symbol":"LSKETH","price":"0.00033730"},{"symbol":"LSKBNB","price":"0.00000000"},{"symbol":"TNTBTC","price":"0.00000000"},{"symbol":"TNTETH","price":"0.00000000"},{"symbol":"FUELBTC","price":"0.00000000"},{"symbol":"FUELETH","price":"0.00000000"},{"symbol":"MANABTC","price":"0.00000147"},{"symbol":"MANAETH","price":"0.00004950"},{"symbol":"BCDBTC","price":"0.00000000"},{"symbol":"BCDETH","price":"0.00000000"},{"symbol":"DGDBTC","price":"0.00000000"},{"symbol":"DGDETH","price":"0.00000000"},{"symbol":"IOTABNB","price":"0.00071700"},{"symbol":"ADXBTC","price":"0.00000091"},{"symbol":"ADXETH","price":"0.00003007"},{"symbol":"ADXBNB","price":"0.00000000"},{"symbol":"ADABTC","price":"0.00000328"},{"symbol":"ADAETH","price":"0.00011730"},{"symbol":"PPTBTC","price":"0.00000000"},{"symbol":"PPTETH","price":"0.00000000"},{"symbol":"CMTBTC","price":"0.00000000"},{"symbol":"CMTETH","price":"0.00000000"},{"symbol":"CMTBNB","price":"0.00000000"},{"symbol":"XLMBTC","price":"0.00000194"},{"symbol":"XLMETH","price":"0.00006943"},{"symbol":"XLMBNB","price":"0.00030360"},{"symbol":"CNDBTC","price":"0.00000000"},{"symbol":"CNDETH","price":"0.00000000"},{"symbol":"CNDBNB","price":"0.00000000"},{"symbol":"LENDBTC","price":"0.00000000"},{"symbol":"LENDETH","price":"0.00000000"},{"symbol":"WABIBTC","price":"0.00000030"},{"symbol":"WABIETH","price":"0.00000000"},{"symbol":"WABIBNB","price":"0.00000000"},{"symbol":"LTCETH","price":"0.02579000"},{"symbol":"LTCUSDT","price":"56.36000000"},{"symbol":"LTCBNB","price":"0.08590000"},{"symbol":"TNBBTC","price":"0.00000000"},{"symbol":"TNBETH","price":"0.00000000"},{"symbol":"WAVESBTC","price":"0.00001626"},{"symbol":"WAVESETH","price":"0.00029800"},{"symbol":"WAVESBNB","price":"0.00513000"},{"symbol":"GTOBTC","price":"0.00000077"},{"symbol":"GTOETH","price":"0.00000000"},{"symbol":"GTOBNB","price":"0.00000000"},{"symbol":"ICXBTC","price":"0.00000056"},{"symbol":"ICXETH","price":"0.00011790"},{"symbol":"ICXBNB","price":"0.00000000"},{"symbol":"OSTBTC","price":"0.00000000"},{"symbol":"OSTETH","price":"0.00000000"},{"symbol":"OSTBNB","price":"0.00000000"},{"symbol":"ELFBTC","price":"0.00000274"},{"symbol":"ELFETH","price":"0.00014330"},{"symbol":"AIONBTC","price":"0.00000139"},{"symbol":"AIONETH","price":"0.00000000"},{"symbol":"AIONBNB","price":"0.00000000"},{"symbol":"NEBLBTC","price":"0.00001200"},{"symbol":"NEBLBNB","price":"0.00000000"},{"symbol":"BRDBTC","price":"0.00000000"},{"symbol":"BRDETH","price":"0.00000000"},{"symbol":"BRDBNB","price":"0.00000000"},{"symbol":"MCOBNB","price":"0.00000000"},{"symbol":"EDOBTC","price":"0.00000000"},{"symbol":"EDOETH","price":"0.00000000"},{"symbol":"WINGSBTC","price":"0.00000000"},{"symbol":"WINGSETH","price":"0.00000000"},{"symbol":"NAVBTC","price":"0.00000000"},{"symbol":"NAVETH","price":"0.00000000"},{"symbol":"NAVBNB","price":"0.00000000"},{"symbol":"LUNBTC","price":"0.00000000"},{"symbol":"LUNETH","price":"0.00000000"},{"symbol":"TRIGBTC","price":"0.00000000"},{"symbol":"TRIGETH","price":"0.00000000"},{"symbol":"TRIGBNB","price":"0.00000000"},{"symbol":"APPCBTC","price":"0.00000000"},{"symbol":"APPCETH","price":"0.00000000"},{"symbol":"APPCBNB","price":"0.00000000"},{"symbol":"VIBEBTC","price":"0.00000000"},{"symbol":"VIBEETH","price":"0.00000000"},{"symbol":"RLCBTC","price":"0.00000553"},{"symbol":"RLCETH","price":"0.00018910"},{"symbol":"RLCBNB","price":"0.00000000"},{"symbol":"INSBTC","price":"0.00000000"},{"symbol":"INSETH","price":"0.00000000"},{"symbol":"PIVXBTC","price":"0.00000147"},{"symbol":"PIVXBNB","price":"0.00000000"},{"symbol":"IOSTBTC","price":"0.00000010"},{"symbol":"IOSTETH","price":"0.00000372"},{"symbol":"CHATBTC","price":"0.00000000"},{"symbol":"CHATETH","price":"0.00000000"},{"symbol":"STEEMBTC","price":"0.00000072"},{"symbol":"STEEMETH","price":"0.00002586"},{"symbol":"STEEMBNB","price":"0.00000000"},{"symbol":"NANOBTC","price":"0.00000000"},{"symbol":"NANOETH","price":"0.00000000"},{"symbol":"NANOBNB","price":"0.00000000"},{"symbol":"VIABTC","price":"0.00000000"},{"symbol":"VIAETH","price":"0.00000000"},{"symbol":"VIABNB","price":"0.00000000"},{"symbol":"BLZBTC","price":"0.00000060"},{"symbol":"BLZETH","price":"0.00004159"},{"symbol":"BLZBNB","price":"0.00000000"},{"symbol":"AEBTC","price":"0.00000000"},{"symbol":"AEETH","price":"0.00000000"},{"symbol":"AEBNB","price":"0.00000000"},{"symbol":"RPXBTC","price":"0.00000000"},{"symbol":"RPXETH","price":"0.00000000"},{"symbol":"RPXBNB","price":"0.00000000"},{"symbol":"NCASHBTC","price":"0.00000000"},{"symbol":"NCASHETH","price":"0.00000000"},{"symbol":"NCASHBNB","price":"0.00000000"},{"symbol":"POABTC","price":"0.00000000"},{"symbol":"POAETH","price":"0.00000000"},{"symbol":"POABNB","price":"0.00000000"},{"symbol":"ZILBTC","price":"0.00000010"},{"symbol":"ZILETH","price":"0.00000168"},{"symbol":"ZILBNB","price":"0.00008858"},{"symbol":"ONTBTC","price":"0.00000075"},{"symbol":"ONTETH","price":"0.00012530"},{"symbol":"ONTBNB","price":"0.00000000"},{"symbol":"STORMBTC","price":"0.00000000"},{"symbol":"STORMETH","price":"0.00000000"},{"symbol":"STORMBNB","price":"0.00000000"},{"symbol":"QTUMBNB","price":"0.00000000"},{"symbol":"QTUMUSDT","price":"0.91900000"},{"symbol":"XEMBTC","price":"0.00000192"},{"symbol":"XEMETH","price":"0.00000000"},{"symbol":"XEMBNB","price":"0.00000000"},{"symbol":"WANBTC","price":"0.00000073"},{"symbol":"WANETH","price":"0.00009270"},{"symbol":"WANBNB","price":"0.00000000"},{"symbol":"WPRBTC","price":"0.00000000"},{"symbol":"WPRETH","price":"0.00000000"},{"symbol":"QLCBTC","price":"0.00000021"},{"symbol":"QLCETH","price":"0.00000000"},{"symbol":"SYSBTC","price":"0.00000019"},{"symbol":"SYSETH","price":"0.00000000"},{"symbol":"SYSBNB","price":"0.00000000"},{"symbol":"QLCBNB","price":"0.00000000"},{"symbol":"GRSBTC","price":"0.00000000"},{"symbol":"GRSETH","price":"0.00000000"},{"symbol":"ADAUSDT","price":"0.25660000"},{"symbol":"ADABNB","price":"0.00039100"},{"symbol":"CLOAKBTC","price":"0.00000000"},{"symbol":"CLOAKETH","price":"0.00000000"},{"symbol":"GNTBTC","price":"0.00000000"},{"symbol":"GNTETH","price":"0.00000000"},{"symbol":"GNTBNB","price":"0.00000000"},{"symbol":"LOOMBTC","price":"0.00000075"},{"symbol":"LOOMETH","price":"0.00003231"},{"symbol":"LOOMBNB","price":"0.00000000"},{"symbol":"XRPUSDT","price":"1.41870000"},{"symbol":"BCNBTC","price":"0.00000000"},{"symbol":"BCNETH","price":"0.00000000"},{"symbol":"BCNBNB","price":"0.00000000"},{"symbol":"REPBTC","price":"0.00034130"},{"symbol":"REPBNB","price":"0.00000000"},{"symbol":"BTCTUSD","price":"74718.58000000"},{"symbol":"TUSDBTC","price":"0.00000000"},{"symbol":"ETHTUSD","price":"2329.19000000"},{"symbol":"TUSDETH","price":"0.00000000"},{"symbol":"TUSDBNB","price":"0.00000000"},{"symbol":"ZENBTC","price":"0.00007646"},{"symbol":"ZENETH","price":"0.00399100"},{"symbol":"ZENBNB","price":"0.03290000"},{"symbol":"SKYCOINBTC","price":"0.00000000"},{"symbol":"SKYCOINETH","price":"0.00000000"},{"symbol":"SKYCOINBNB","price":"0.00000000"},{"symbol":"EOSUSDT","price":"0.77990000"},{"symbol":"EOSBNB","price":"0.00258300"},{"symbol":"CVCBTC","price":"0.00000566"},{"symbol":"CVCETH","price":"0.00000000"},{"symbol":"CVCBNB","price":"0.00000000"},{"symbol":"THETABTC","price":"0.00000258"},{"symbol":"THETAETH","price":"0.00050170"},{"symbol":"THETABNB","price":"0.00273600"},{"symbol":"XRPBNB","price":"0.00216490"},{"symbol":"TUSDUSDT","price":"1.00000000"},{"symbol":"IOTAUSDT","price":"0.05640000"},{"symbol":"XLMUSDT","price":"0.15200000"},{"symbol":"IOTXBTC","price":"0.00000009"},{"symbol":"IOTXETH","price":"0.00000300"},{"symbol":"QKCBTC","price":"0.00000010"},{"symbol":"QKCETH","price":"0.00000430"},{"symbol":"AGIBTC","price":"0.00000000"},{"symbol":"AGIETH","price":"0.00000000"},{"symbol":"AGIBNB","price":"0.00000000"},{"symbol":"NXSBTC","price":"0.00000000"},{"symbol":"NXSETH","price":"0.00000000"},{"symbol":"NXSBNB","price":"0.00000000"},{"symbol":"ENJBNB","price":"0.00136800"},{"symbol":"DATABTC","price":"0.00000008"},{"symbol":"DATAETH","price":"0.00002034"},{"symbol":"ONTUSDT","price":"0.05800000"},{"symbol":"TRXBNB","price":"0.00054080"},{"symbol":"TRXUSDT","price":"0.35430000"},{"symbol":"ETCUSDT","price":"9.12000000"},{"symbol":"ETCBNB","price":"0.01416000"},{"symbol":"ICXUSDT","price":"0.03660000"},{"symbol":"SCBTC","price":"0.00000000"},{"symbol":"SCETH","price":"0.00000049"},{"symbol":"NPXSBTC","price":"0.00000000"},{"symbol":"NPXSETH","price":"0.00000000"},{"symbol":"VENUSDT","price":"0.00000000"},{"symbol":"KEYBTC","price":"0.00000000"},{"symbol":"KEYETH","price":"0.00000227"},{"symbol":"NASBTC","price":"0.00000000"},{"symbol":"NASETH","price":"0.00000000"},{"symbol":"NASBNB","price":"0.00000000"},{"symbol":"MFTBTC","price":"0.00000000"},{"symbol":"MFTETH","price":"0.00000433"},{"symbol":"MFTBNB","price":"0.00000000"},{"symbol":"DENTBTC","price":"0.00000000"},{"symbol":"DENTETH","price":"0.00000007"},{"symbol":"ARDRBTC","price":"0.00000065"},{"symbol":"ARDRETH","price":"0.00000000"},{"symbol":"ARDRBNB","price":"0.00000000"},{"symbol":"NULSUSDT","price":"0.02580000"},{"symbol":"HOTBTC","price":"0.00000000"},{"symbol":"HOTETH","price":"0.00000017"},{"symbol":"VETBTC","price":"0.00000009"},{"symbol":"VETETH","price":"0.00000344"},{"symbol":"VETUSDT","price":"0.00684300"},{"symbol":"VETBNB","price":"0.00001339"},{"symbol":"DOCKBTC","price":"0.00000005"},{"symbol":"DOCKETH","price":"0.00000000"},{"symbol":"POLYBTC","price":"0.00001384"},{"symbol":"POLYBNB","price":"0.00000000"},{"symbol":"PHXBTC","price":"0.00000000"},{"symbol":"PHXETH","price":"0.00000000"},{"symbol":"PHXBNB","price":"0.00000000"},{"symbol":"HCBTC","price":"0.00000000"},{"symbol":"HCETH","price":"0.00000000"},{"symbol":"GOBTC","price":"0.00000000"},{"symbol":"GOBNB","price":"0.00000000"},{"symbol":"PAXBTC","price":"0.00000000"},{"symbol":"PAXBNB","price":"0.00000000"},{"symbol":"PAXUSDT","price":"0.00000000"},{"symbol":"PAXETH","price":"0.00000000"},{"symbol":"RVNBTC","price":"0.00000010"},{"symbol":"DCRBTC","price":"0.00021850"},{"symbol":"DCRBNB","price":"0.00000000"},{"symbol":"USDCBNB","price":"0.00000000"},{"symbol":"MITHBTC","price":"0.00000080"},{"symbol":"MITHBNB","price":"0.00004410"},{"symbol":"BCHABCBTC","price":"0.00000000"},{"symbol":"BCHSVBTC","price":"0.00000000"},{"symbol":"BCHABCUSDT","price":"0.00000000"},{"symbol":"BCHSVUSDT","price":"0.00000000"},{"symbol":"BNBPAX","price":"0.00000000"},{"symbol":"BTCPAX","price":"0.00000000"},{"symbol":"ETHPAX","price":"0.00000000"},{"symbol":"XRPPAX","price":"0.00000000"},{"symbol":"EOSPAX","price":"0.00000000"},{"symbol":"XLMPAX","price":"0.00000000"},{"symbol":"RENBTC","price":"0.00000043"},{"symbol":"RENBNB","price":"0.00000000"},{"symbol":"BNBTUSD","price":"605.48000000"},{"symbol":"XRPTUSD","price":"1.31780000"},{"symbol":"EOSTUSD","price":"0.00000000"},{"symbol":"XLMTUSD","price":"0.00000000"},{"symbol":"BNBUSDC","price":"655.34000000"},{"symbol":"BTCUSDC","price":"78150.72000000"},{"symbol":"ETHUSDC","price":"2185.30000000"},{"symbol":"XRPUSDC","price":"1.41840000"},{"symbol":"EOSUSDC","price":"0.77780000"},{"symbol":"XLMUSDC","price":"0.15170000"},{"symbol":"USDCUSDT","price":"1.00021000"},{"symbol":"ADATUSD","price":"0.38470000"},{"symbol":"TRXTUSD","price":"0.05986000"},{"symbol":"NEOTUSD","price":"0.00000000"},{"symbol":"TRXXRP","price":"0.24980000"},{"symbol":"XZCXRP","price":"0.00000000"},{"symbol":"PAXTUSD","price":"0.00000000"},{"symbol":"USDCTUSD","price":"0.00000000"},{"symbol":"USDCPAX","price":"0.00000000"},{"symbol":"LINKUSDT","price":"9.79000000"},{"symbol":"LINKTUSD","price":"14.42300000"},{"symbol":"LINKPAX","price":"0.00000000"},{"symbol":"LINKUSDC","price":"9.79000000"},{"symbol":"WAVESUSDT","price":"1.07600000"},{"symbol":"WAVESTUSD","price":"0.00000000"},{"symbol":"WAVESPAX","price":"0.00000000"},{"symbol":"WAVESUSDC","price":"0.00000000"},{"symbol":"BCHABCTUSD","price":"0.00000000"},{"symbol":"BCHABCPAX","price":"0.00000000"},{"symbol":"BCHABCUSDC","price":"0.00000000"},{"symbol":"BCHSVTUSD","price":"0.00000000"},{"symbol":"BCHSVPAX","price":"0.00000000"},{"symbol":"BCHSVUSDC","price":"0.00000000"},{"symbol":"LTCTUSD","price":"83.07000000"},{"symbol":"LTCPAX","price":"0.00000000"},{"symbol":"LTCUSDC","price":"56.37000000"},{"symbol":"TRXPAX","price":"0.00000000"},{"symbol":"TRXUSDC","price":"0.35420000"},{"symbol":"BTTBTC","price":"0.00000000"},{"symbol":"BTTBNB","price":"0.00000000"},{"symbol":"BTTUSDT","price":"0.00000000"},{"symbol":"BNBUSDSOLD","price":"0.00000000"},{"symbol":"BTCUSDSOLD","price":"0.00000000"},{"symbol":"USDSOLDUSDT","price":"0.00000000"},{"symbol":"USDSOLDPAX","price":"0.00000000"},{"symbol":"USDSOLDTUSD","price":"0.00000000"},{"symbol":"USDSOLDUSDC","price":"0.00000000"},{"symbol":"BTTPAX","price":"0.00000000"},{"symbol":"BTTTUSD","price":"0.00000000"},{"symbol":"BTTUSDC","price":"0.00000000"},{"symbol":"ONGBNB","price":"0.00000000"},{"symbol":"ONGBTC","price":"0.00000085"},{"symbol":"ONGUSDT","price":"0.06650000"},{"symbol":"HOTBNB","price":"0.00000000"},{"symbol":"HOTUSDT","price":"0.00040700"},{"symbol":"ZILUSDT","price":"0.00400000"},{"symbol":"ZRXBNB","price":"0.00000000"},{"symbol":"ZRXUSDT","price":"0.10880000"},{"symbol":"FETBNB","price":"0.00029820"},{"symbol":"FETBTC","price":"0.00000252"},{"symbol":"FETUSDT","price":"0.19690000"},{"symbol":"BATUSDT","price":"0.09870000"},{"symbol":"XMRBNB","price":"0.33210000"},{"symbol":"XMRUSDT","price":"118.70000000"},{"symbol":"ZECBNB","price":"0.10260000"},{"symbol":"ZECUSDT","price":"516.86000000"},{"symbol":"ZECPAX","price":"0.00000000"},{"symbol":"ZECTUSD","price":"0.00000000"},{"symbol":"ZE

In [109]:
tickers = response.json()

In [110]:
tickers[0:10]

[{'symbol': 'ETHBTC', 'price': '0.02797000'},
 {'symbol': 'LTCBTC', 'price': '0.00072100'},
 {'symbol': 'BNBBTC', 'price': '0.00838800'},
 {'symbol': 'NEOBTC', 'price': '0.00003542'},
 {'symbol': 'QTUMETH', 'price': '0.00046550'},
 {'symbol': 'EOSETH', 'price': '0.00030670'},
 {'symbol': 'SNTETH', 'price': '0.00001700'},
 {'symbol': 'BNTETH', 'price': '0.00020260'},
 {'symbol': 'BCCBTC', 'price': '0.00000000'},
 {'symbol': 'GASBTC', 'price': '0.00002070'}]

In [111]:
df = pd.DataFrame(tickers)

In [112]:
df[df.symbol == 'BTCUSDT']

     symbol           price
11  BTCUSDT  78155.83000000

In [113]:
df = pd.read_csv("sample_data/eurostat_hicpv2.csv")

In [114]:
eu_inflations = df.iloc[6:]

In [115]:
eu_inflations.info()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 6 to 40
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   geo     35 non-null     str
 1   2008    35 non-null     float64
 2   2009    35 non-null     float64
 3   2010    35 non-null     float64
 4   2011    35 non-null     float64
 5   2012    35 non-null     float64
 6   2013    35 non-null     float64
 7   2014    35 non-null     float64
 8   2015    35 non-null     float64
 9   2016    35 non-null     float64
 10  2017    35 non-null     float64
 11  2018    35 non-null     float64
 12  2019    35 non-null     float64
dtypes: float64(12), str(1)
memory usage: 3.7 KB

In [116]:
eu_inflations

,geo,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
6,Belgium,4.5,0.0,2.3,3.4,2.6,1.2,0.5,0.6,1.8,2.2,2.3,1.2
7,Bulgaria,12.0,2.5,3.0,3.4,2.4,0.4,-1.6,-1.1,-1.3,1.2,2.6,2.5
8,Czechia,6.3,0.6,1.2,2.2,3.5,1.4,0.4,0.3,0.6,2.4,2.0,2.6
9,Denmark,3.6,1.0,2.2,2.7,2.4,0.5,0.4,0.2,0.0,1.1,0.7,0.7
10,Germany,2.8,0.2,1.1,2.5,2.2,1.6,0.8,0.7,0.4,1.7,1.9,1.4
11,Estonia,10.6,0.2,2.7,5.1,4.2,3.2,0.5,0.1,0.8,3.7,3.4,2.3
12,Ireland,3.1,-1.7,-1.6,1.2,1.9,0.5,0.3,0.0,-0.2,0.3,0.7,0.9
13,Greece,4.2,1.3,4.7,3.1,1.0,-0.9,-1.4,-1.1,0.0,1.1,0.8,0.5
14,Spain,4.1,-0.2,2.0,3.0,2.4,1.5,-0.2,-0.6,-0.3,2.0,1.7,0.8
15,France,3.2,0.1,1.7,2.3,2.2,1.0,0.6,0.1,0.3,1.2,2.1,1.3
16,Croatia,5.8,2.2,1.1,2.2,3.4,2.3,0.2,-0.3,-0.6,1.3,1.6,0.8
17,Italy,3.5,0.8,1.6,2.9,3.3,1.2,0.2,0.1,-0.1,1.3,1.2,0.6
18,Cyprus,4.4,0.2,2.6,3.5,3.1,0.4,-0.3,-1.5,-1.2,0.7,0.8,0.5
19,Latvia,15.3,3.3,-1.2,4.2,2.3,0.0,0.7,0.2,0.1,2.9,2.6,2.7
20,Lithuania,11.1,4.2,1.2,4.1,3.2,1.2,0.2,-0.7,0.7,3.7,2.5,2.2
21,Luxembourg,4.1,0.0,2.8,3.7,2.9,1.7,0.7,0.1,0.0,2.1,2.0,1.6
22,Hungary,6.0,4.0,4.7,3.9,5.7,1.7,0.0,0.1,0.4,2.4,2.9,3.4
23,Malta,4.7,1.8,2.0,2.5,3.2,1.0,0.8,1.2,0.9,1.3,1.7,1.5
24,Netherlands,2.2,1.0,0.9,2.5,2.8,2.6,0.3,0.2,0.1,1.3,1.6,2.7
25,Austria,3.2,0.4,1.7,3.6,2.6,2.1,1.5,0.8,1.0,2.2,2.1,1.5
26,Poland,4.2,4.0,2.6,3.9,3.7,0.8,0.1,-0.7,-0.2,1.6,1.2,2.1
27,Portugal,2.7,-0.9,1.4,3.6,2.8,0.4,-0.2,0.5,0.6,1.6,1.2,0.3
28,Romania,7.9,5.6,6.1,5.8,3.4,3.2,1.4,-0.4,-1.1,1.1,4.1,3.9
29,Slovenia,5.5,0.8,2.1,2.1,2.8,1.9,0.4,-0.8,-0.2,1.6,1.9,1.7
30,Slovakia,3.9,0.9,0.7,4.1,3.7,1.5,-0.1,-0.3,-0.5,1.4,2.5,2.8
31,Finland,3.9,1.6,1.7,3.3,3.2,2.2,1.2,-0.2,0.4,0.8,1.2,1.1
32,Sweden,3.3,1.9,1.9,1.4,0.9,0.4,0.2,0.7,1.1,1.9,2.0,1.7
33,United Kingdom,3.6,2.2,3.3,4.5,2.8,2.6,1.5,0.0,0.7,2.7,2.5,1.8
34,Iceland,12.8,16.3,7.5,4.2,6.0,4.1,1.0,0.3,0.8,-1.7,0.7,2.0
35,Norway,3.4,2.3,2.3,1.3,0.4,2.0,1.9,2.0,3.9,1.9,3.0,2.3
36,Switzerland,2.4,-0.7,0.6,0.1,-0.7,0.1,0.0,-0.8,-0.5,0.6,0.9,0.4
37,North Macedonia,7.6,-0.1,1.1,3.2,1.8,2.7,0.0,0.1,0.2,2.1,2.3,0.7
38,Serbia,11.9,8.2,6.2,11.2,7.4,7.7,2.3,1.5,1.3,3.3,2.0,1.9
39,Turkey,10.4,6.3,8.6,6.5,9.0,7.5,8.9,7.7,7.7,11.1,16.3,15.2
40,United States,4.4,-0.8,2.6,3.9,2.2,1.3,1.3,-0.8,0.5,1.7,2.2,1.3

In [117]:
years = eu_inflations.columns.to_list()[1:]

In [118]:
inflations = pd.melt(frame=eu_inflations, id_vars='geo', value_vars=years, var_name="years", value_name="inflation_rate")

In [119]:
covid19_df = pd.json_normalize(pd.read_json("sample_data/covid19-stream-data.json")['records'])

In [120]:
covid19_df.columns

Index(['dateRep', 'day', 'month', 'year', 'cases', 'deaths',
       'countriesAndTerritories', 'geoId', 'countryterritoryCode',
       'popData2019', 'continentExp',
       'Cumulative_number_for_14_days_of_COVID-19_cases_per_100000'],
      dtype='str')

In [121]:
covid19_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61900 entries, 0 to 61899
Data columns (total 12 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   dateRep                                                     61900 non-null  str
 1   day                                                         61900 non-null  str
 2   month                                                       61900 non-null  str
 3   year                                                        61900 non-null  str
 4   cases                                                       61900 non-null  int64
 5   deaths                                                      61900 non-null  int64
 6   countriesAndTerritories                                     61900 non-null  str
 7   geoId                                                       61900 non-null  str
 8   countryterritoryCode                                        61777 non-null  str
 9   popData2019                                                 61777 non-null  float64
 10  continentExp                                                61900 non-null  str
 11  Cumulative_number_for_14_days_of_COVID-19_cases_per_100000  61900 non-null  str
dtypes: float64(1), int64(2), str(9)
memory usage: 5.7 MB

In [122]:
covid19_df.describe()

               cases        deaths   popData2019
count   61900.000000  61900.000000  6.177700e+04
mean     1155.147237     26.055460  4.098770e+07
std      6779.224479    131.227055  1.531294e+08
min     -8261.000000  -1918.000000  8.150000e+02
25%         0.000000      0.000000  1.293120e+06
50%        15.000000      0.000000  7.169456e+06
75%       273.000000      4.000000  2.851583e+07
max    234633.000000   4928.000000  1.433784e+09

In [123]:
turkish_covid_results = covid19_df[covid19_df.countryterritoryCode == 'TUR']

In [124]:
turkish_covid_results.to_csv("sample_data/turkish-covid19.csv")

In [125]:
turkish_covid_results.to_json("sample_data/turkish-covid19.json")

In [126]:
%pip install openpyxl
turkish_covid_results.to_excel("sample_data/turkish-covid19.xlsx")

Requirement already satisfied: openpyxl in .\.venv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in .\.venv\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.